version: '3'

services:

  nginx:
    build: docker/nginx/
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./php:/www
    ports:
      - "8081:80"


  php:
    build: docker/php/
    volumes:
      - ./php:/www


volumes:
  nginx_conf: